name: Bump version
on:
  workflow_dispatch:
  workflow_call:
      
jobs:

  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        WITH_V: false
