name: Bump version
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Swift Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build

  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        WITH_V: false
