name: CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
    
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    strategy:
      matrix:
        packages:
          - OversizeServices
          - OversizeStoreService
          - OversizeLocationService
          - OversizeCalendarService
          - OversizeContactsService
          - OversizeNotificationService
          - OversizeFileManagerService
    with:
      package: ${{ matrix.packages }}
    secrets: inherit
    
  tests:
    name: Test
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
    secrets: inherit
    
  bump:
    name: Bump version
    needs: tests
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
    
