name: CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
    
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages:
          - OversizeServices
          - OversizeStoreService
          - OversizeLocationService
          - OversizeCalendarService
          - OversizeContactsService
          - OversizeNotificationService
          - OversizeFileManagerService
        destination:
          - platform=iOS Simulator,name=iPhone 17,OS=26.2
          - platform=watchOS Simulator,name=Apple Watch SE 3 (40mm),OS=26.2
          - platform=tvOS Simulator,name=Apple TV 4K (3rd generation) (at 1080p),OS=26.2
          - platform=macOS,arch=arm64
          
    with:
      package: ${{ matrix.packages }}
      destination: ${{ matrix.destination }}
    secrets: inherit
    
#  tests:
#    name: Test
#    needs: build-swiftpm
#    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
#    secrets: inherit
    
  bump:
    name: Bump version
    needs: build-swiftpm
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
    
