name: CI - Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
    
  build-swiftpm:
    name: Build packages
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages: [OversizeServices, OversizeHealthService, OversizeCloudKitService, OversizeStoreService, OversizeLocationService, OversizeCalendarService, OversizeContactsService, OversizeNotificationService, OversizeFileManagerService]
    with:
      package: ${{ matrix.packages }}
    secrets: inherit
    
  # tests:
  #   name: Test
  #   needs: build-swiftpm
  #   uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
  #   secrets: inherit
    
  bump:
    name: Bump version
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
    
