name: CI - Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:

  build-swiftpm:
    name: Build SwiftPM
    uses: ./.github/workflows/actions/build-swiftpm/build-swiftpm.yml
    secrets: inherit
    
  tests:
    name: Test
    needs: build-swiftpm
    uses: ./.github/workflows/actions/test/test.yml
    secrets: inherit
    
  bump:
    name: Bump version
    needs: tests
    uses: ./.github/workflows/actions/bump/bump.yml
    secrets: inherit
    
